//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripeFundamentals.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public Plan()
        {
            this.Features = new HashSet<Feature>();
        }
    
        public int Id { get; set; }
        public string ExternalId { get; set; }
        public string Description { get; set; }
        public string CSSThemeClasses { get; set; }
        public string CSSThemeButtonClasses { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Feature> Features { get; set; }
    }
}
